% Create cohort list, tmasks, and tmask list for ABCD
subjects = textread('/data/nil-bluearc/GMT/ABCD/Initial_Subjectlist_287.txt','%s','delimiter','\n');
% Col 1 = subject 
% Col 2 = full path of the surface-mapped (cifti-space) functional data
% Col 3 = directory where the subject's surface is (as generated by Freesurfer and registered to fs_LR space)
for s = 1:size(subjects,1)
    subject = subjects{s};
    subjects{s,2} = ['/data/nil-bluearc/GMT/ABCD/initial_ABCD_data/' subject '/MNINonLinear/Results/' subject '_rfMRI_REST_FNL_preproc_v2_Atlas.dtseries.nii'];
    subjects{s,3} = ['/data/nil-bluearc/GMT/ABCD/initial_ABCD_data/' subject '/MNINonLinear/fsaverage_LR32k/'];
end
cell2txtfile('/data/nil-bluearc/GMT/Scott/ABCD/cohortfile.txt',subjects)

% Tmask list 
% Col 1 = subject
% Col 2 = full path to tmask list ... generated below
subjects = textread('/data/nil-bluearc/GMT/ABCD/Initial_Subjectlist_287.txt','%s','delimiter','\n');
for s = 1:size(subjects,1)
    subject = subjects{s};
    subjects{s,2} = ['/data/nil-bluearc/GMT/Scott/ABCD/TMASK/' subject '_TMASK.txt'];
end
cell2txtfile('/data/nil-bluearc/GMT/Scott/ABCD/tmasklist.txt',subjects)

% Generate Tmasks
for s = 1:size(subjects,1)
    subject = subjects{s};
    % Temp masks
    % Check # of runs 
    a = dir(['/data/nil-bluearc/GMT/ABCD/initial_ABCD_data/' subject '/*rfMRI_REST*']);
    n = numel(a);
    FD = [];
    % Read in FD files, concatenate, & binarize at thr = 0.2
    for run = 1:n
        ThisFD = load(['/data/nil-bluearc/GMT/ABCD/initial_ABCD_data/' subject '/MNINonLinear/Results/rfMRI_REST' num2str(run) '/FNL_preproc_v2/FD.mat']);
        data = zeros(1+length(ThisFD.FD),1);
        data(1) = 0; data(2:end) = ThisFD.FD;
        FD = [FD; data];
    end
    FD(FD>=.2)=0; FD(FD<.2 & FD > 0) = 1;
    
    % Write text file
    output_file = fopen(['/data/nil-bluearc/GMT/Scott/ABCD/TMASK/' subject '_TMASK.txt'],'w'); 
   
    fprintf(output_file,'%0.1f \n',FD); 
   
    fclose(output_file); 
    
end

